### ISSUE TITLE
Add allocator support

### ISSUE THREAD

**Issue by anthonywilliams** [jbcoe/polymorphic_value#107]
The `polymorphic_value` object allocates memory, so it ought to be customizable with an allocator.

The allocator can be stored inside the control block, and used to allocate copies.

**Comment by jbcoe** [comment]
We _think_ this might be possible. Allocator support was removed from std::function because of implementation divergence according to https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0302r0.html 

If we can implement allocator support well then maybe we can clearly specify all the behaviour.

**Comment by jbcoe** [comment]
Closed by #110
