### ISSUE TITLE
add/reinstate get() accessor

### ISSUE THREAD

**Issue by frankheckenbach** [jbcoe/polymorphic_value#83]
(The paper says: "Remove pointer-accessor get." I found no trace of it in the history, but I suppose this was before it was on Github.)

Anyway, I'm trying out polymorphic_value in a project of mine, and already found some cases where I'd need such an accessor (which I suppose was like the one of std::unique_ptr), e.g.:
- finding a polymorphic object in a container by identity, not value, i.e. comparing addresses
- downcasting via dynamic_cast

Of course, I can work-around it with "&*", but that looks ugly -- in the 2nd case, combined with an iterator, I have to say "dynamic_cast <T *> (&**i)" instead of "dynamic_cast <T *> (i->get ())".

I think that's some evidence that get() might be useful after all. Also, it would make conversion from unique_ptr to polymorphic_value (like I just did) a bit smoother.

**Comment by jbcoe** [comment]
I'm sympathetic to your request but it is possible (albeit ugly) to get access to the underlying pointer.

Adding `get()` would mean that `polymorphic_value` models a pointer like `std::unique_ptr` or `std::shared_ptr`. 

Like `std::optional`(another value type), `polymorphic_value` does not provide `get()`.

This is by design and by request of the C++ Library Evolution Working Group.
